# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
variables:
  - group: vgtest

resources:
  repositories:
    - repository: templates
      type: github
      name: lizaoa/az_group
      #ref: refs/tags/v1.0 # optional ref to pin to
      endpoint: TestProj

jobs:
- template: comm.yml@templates  # Template reference
  parameters:
    c1: 'windows of latest'

- job: another
  steps:
  - script: echo aaaaaa-- $(vgva1)