pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
     foo: 
       FOO1
       FOO2
       FOO3
     bar: BARS




steps:
- ${{ each a in parameters.myObject }}:
      - script: echo ${{ a.value.value }}