# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  #vmImage: windows-latest
  name: my-win-pools
steps:
- powershell: powershell(new-object system.net.webclient).downloadfile('https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip','aaa.zip')
- powershell: powershell -c " Expand-Archive aaa.zip ."
- script: powershell gg.ps1
- powershell: WRITE-HOST now isYY---YYY $env:PATH
- powershell: mvn package
  displayName: 'Build with lI-new Maven'