# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: lizaoa/az_group
      #ref: refs/tags/v1.0 # optional ref to pin to
      endpoint: TestProj

jobs:
- template: comm.yml@templates  # Template reference
  parameters:
    c1: 'windows-latest'