# File: azure-pipelines.yml

# This will fail since it doesn't set the "solution" parameter to anything,
# so the template will use its default of an empty string
pool:
  vmimage: windows-latest
steps:
- template: steps/msbuild.yml
  parameters:
      solution: abcde