parameters:
- name: 'restoreProjects'
  default: 'aaaa'
  type: string
- name: 'buildProjects'
  default: 'bbbb'
  type: string

steps:
- script: echo ${{ coalesce(parameters.restoreProjects, parameters.buildProjects, 'Nothing to see') }}