parameters:
- name: 'solution'
  default: 'abcde'
  type: string
pool:
 name: my-win-pools
steps:
- bash: |
    if [ -z "aaa" ]: then
      echo "##vso[task.logissue type=error;]Missing template LI parameter \"solution\""
      echo "##vso[task.complete result=Failed;]"
    fi
  env:
    SOLUTION: ${{ parameters.solution }}
  displayName: Check for required parameters
- bash: echo ${{ parameters.solution }}