pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    foo: FOO
    things:
    - one
    - two
    - three

steps:
- ${{ each a in parameters.myObject }}:
      - ${{ if eq(a.value,'things') }}:
        - ${{ each b in a.value }}:      
          - script: echo ttttt  --${{ b }} -- ${{ b.value }}