pool:
  name: my-win-pools

trigger:
  - none

resources:
 repositories:
   - repository: templates
     type: github
     name: lizaoa/az_group
     endpoint: myServiceConnection

  
steps:
- template: comm.yml@templates
  parameters:
    c1: 'wwww'