# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
variables:
  - group: vgtest

pool:
  name: my-win-pools

trigger:
   none

resources:
  repositories:
    - repository: Myrep
      type: github
      name: lizaoa/az_group
      #ref: refs/tags/v1.0 # optional ref to pin to
      endpoint: TestProj

steps:
  - checkout: https://github.com/lizaoa/az_group@refs/tags/v1.0
  - script: dir $(build.sourcesdirectory)

