pool:
  name: my-win-pools

trigger:
  - none
variables:
  asd: 111
  
parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - a1: 111
    - b1: 222         
steps:
- ${{ each step in parameters.myobject }}:
    - ${{ if eq( asd,'111') }}:
          - script: echo gggg --${{ step.a1 }}--${{ step.a1.value }}