pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - foo: FOO
    - bar: BAR
    # things:
    # - one1
    # - two2
    # - three
    # nested:
    #   one: apple
    #   two: pear
    #   count: 3


steps:
- ${{ each a in parameters.myObject }}:
      - script: echo ${{ a.value }}
