parameters:

- name: myMultiString
  type: string
  default: default
  values:
  - default
  - ubuntu
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two

trigger: none

jobs: 
- job: stepList
  steps: 
  - ${{ each step in parameters.mySteplist }}:
      - ${{ each pair in step }}:
            ${{ pair.key }}: ${{ pair.value }}   # ${{ pair.key }}: ${{ pair.value }}
# - job: myStep
#   steps:
#     - ${{ parameters.myStep }}