# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
variables:
  - group: vgtest

trigger:
   none

resources:
  repositories:
    - repository: templates
      type: github
      name: lizaoa/az_group
      #ref: refs/tags/v1.0 # optional ref to pin to
      endpoint: TestProj


jobs:
- job: another
  steps:
  - script: echo aaaaaa-- $(vgva1)
  - checkout: git://TestProj/az_group@regs/taags/v1.0


- template: comm.yml@templates  # Template reference
  parameters:
    c1: 'UUUUU windows of latest'

