parameters:
- name: 'solution'
  default: 'VVV'
  type: string
pool:
 name: my-win-pools
steps:
- bash: |
    if [ -z $SOLUTION ]; then
      echo IS NULL AND $SOLUTION
    fi
  env:
    SOLUTION: ${{ parameters.solution }}
  displayName: Check for required parameters
- bash: echo ${{ parameters.solution }}