pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - bash:
        aaaa:
           bbb:vvv            
steps:
- ${{ each step in parameters.myobject }}:
    - ${{ if eq(parameters.myobject.bash.aaaa.bbb,'vvv') }}:
          - script: echo gggg --