pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - one: 1
    - two: 2
    - three: 3

steps:
- ${{ each pair in parameters.myObject }}:
#      - ${{ if eq(a.one,'1') }}:
#        - ${{ each b in a.value }}:      
          - script: echo ttt --${{ pair.key }}----${{ pair.value}}--${{ pair.two}}