# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  #vmImage: windows-latest
  name: my-win-pools
steps:
- script: |
    echo Starting the build
    mvn package
  displayName: 'Build with Maven'
