# File: azure-pipelines.yml


trigger:
- nb

pool:
  name: my-win-pools
parameters:
- name: yesno
  type: boolean
  default: true

steps:
  - ${{ if eq(parameters.yesno,true) }}:
    - bash: echo "it is true"
