pool:
  name: my-win-pools

trigger:
  - none

variables:
  asd: 111
  bef: Nbaa
  
parameters:
- name: myString
  type: string
  default: aaa ${{variables.bef}} ccc
- name: myObject
  type: object
  default: 
    - a1: 111
    - b1: 222         


steps:
- script: echo this is ${{parameters.mystring}}