pool:
  name: my-win-pools

trigger:
  - none

  
parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - a1: 111
    - b1: 222         

variables:
  asd: 111
  bef: Nb NNB ${{parameters.mystring}}--


steps:
- script: echo this is ${{variables.bef}}