pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: stepList
  default: 
    - bash: echo one 1
    - script: echo three 3
    - task: wwww
      inputs: 
         script: echo eeee

steps:
- ${{ each step in parameters.myObject }}:
  - ${{ each pair in step }}:
#      - ${{ if eq(a.one,'1') }}:
#        - ${{ each b in a.value }}:      
          - script: echo gggg --'${{ pair.key }}'--'${{ pair.value.CmdLine }}'---'${{ pair.CmdLine }}'