pool:
  name: my-win-pools

trigger:
  - none

parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - one: 1
    - two: 2
    - three: 3

steps:
- ${{ each a in parameters.myObject }}:
#      - ${{ if ne(a.value,'FOO') }}:
#        - ${{ each b in a.value }}:      
          - script: echo ttttt  ----${{ a.two }}