# File: azure-pipelines.yml


trigger:
- nb

pool:
  name: my-win-pools
parameters:
- name: yesno
  type: string
  default: trues

steps:
  - ${{ if eq(parameters.yesno,'trues') }}:
    - bash: echo "it is trues"
