pool:
  name: my-win-pools
  #vmimage: ubuntu-latest

trigger:
  none

jobs:
- template: job.yml
  parameters:
    jobs:
    - job: A
      steps:
      - script: echo This will get jobAAAa
    - job: B
      steps:
      - script: echo So will this!get jobBBBBBb