# File: azure-pipelines.yml
trigger:
- nb

extends:
  template: start.yml
  parameters:
    buildSteps:  
      - bash: echo "Test -1"
        displayName: succeed -1
      - task: CmdLine@2
        inputs:
          script: echo "Script Test -2"
     
      - script: echo "Script Test - 3"
