# File: azure-pipelines.yml


trigger:
- nb

pool:
  name: my-win-pools
parameters:
- name: yesnos
  type: boolean
  default: false
steps:
  - template: sim.yml
  
  - script: echo disp is ${{ parameters.yesnos }}
