pool:
  name: my-win-pools

trigger:
  - none

  
parameters:
- name: myString
  type: string
  default: a string
- name: myObject
  type: object
  default: 
    - a1: 111
    - b1: 222         

variables:
  asd: 111
  bef: "Nb ${{ parameters.mystring }} NNB"


steps:
- ${{ each step in parameters.myobject }}:
  - ${{ if eq( variables.asd,'1121') }}:
     - script: echo gggg--${{ step.a1 }}--${{ step.a1.value }}
- script: bash $(bef)