# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  #vmImage: windows-latest
  name: my-win-pools
steps:
- powershell: powershell(new-object system.net.webclient).downloadfile('https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip','aaa.zip')
- powershell: powershell -c " Expand-Archive aaa.zip ."
#- powershell: INVOKE [Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";c:\agent\_work\1\s\apache-maven-3.8.6\bin", "User")  
- powershell:  write-host old isXXX $env:PATH
- script: |
     $PATH = $PATH;c:\agent\_work\1\s\apache-maven-3.8.6\bin
- powershell: WRITE-HOST now isYYY $env:PATH
- powershell: mvn package
  displayName: 'Build with lI-new Maven'