# File: azure-pipelines.yml
trigger:
- nb
pool:
 name: my-win-pools
extends:
  template: start.yml
  parameters:
    buildSteps:  
      - bash: echo Test1
        displayName: succeed -1
      - task: CmdLine@2
        inputs:
          script: echo "Script Test -2"
     
      - script: echo "Script Test - 3"
