# File: steps/build.yml
parameters:
- name: 'toolset'
  default: msbuild
  type: string
  values:
  - msbuild
  - dotnet

steps:
# msbuild
- ${{ if eq(parameters.toolset, 'msbuild') }}:
  - script: echo msbuild-1

# dotnet
- ${{ if eq(parameters.toolset, 'dotnet') }}:
  - script: echo dotnet-1

