# job.yml
parameters:
- name: 'jobs'
  type: jobList
  default: []

jobs:
- ${{ each job in parameters.jobs }}: # Each job
  - ${{ each pair in job }}:          # Insert all properties other than "steps"
        ${{ if ne(pair.key, 'steps') }}:
          ${{ pair.key }}: ${{ pair.value }}
    steps:                            # Wrap the steps
    - bash: echo Pre Task       # Pre steps
    - ${{ job.steps }}                # Users steps
    - bash: echo Post Task      # Post steps
      condition: always()
